# Generated by Django 5.0 on 2023-12-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=200)),
                ('Lname', models.CharField(max_length=200)),
                ('Age', models.CharField(max_length=200)),
                ('Dob', models.DateField()),
                ('Quali', models.CharField(max_length=200)),
                ('Lang', models.CharField(max_length=200)),
            ],
        ),
    ]
