# Generated by Django 5.0 on 2024-01-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queryt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryemail', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='query',
        ),
    ]
