# Generated by Django 5.0 on 2024-01-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_queryt_delete_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryt',
            old_name='query',
            new_name='Query',
        ),
        migrations.RenameField(
            model_name='queryt',
            old_name='queryemail',
            new_name='QueryEmail',
        ),
    ]
